### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#10]
Draft three versions of mockups before next week's class for group feedback and changes
Have final draft ready on Monday to lock in final design

**Comment by NinaTanneberger** [comment]
So Jack has uploaded a mockup for us to look at in the Mockups folder.

Feedback:
It's a start but it doesn't look like a complete website yet. Have a look at the Client Full Breakdown file in the Documentation folder. Specifically think about using the colours more for accents on the page and headings. Also the example websites that are listed for layout and colour schemes can give you some ideas and inspiration. Getting the look and feel of the site is the first step so concentrate on nailing the tone of the home screen then you can style the other pages to match. Doing a sitemap will help you get an idea of the main information that should be displayed in terms of importance so it would be beneficial as well.

Jackson and Gary how have you been going with looking into UX UI ideas for the site?

**Comment by JacksonGartner** [comment]
Finish CIU presentation yesturday and just got back from work. Will have research to upload tonight. Is there a document / folder I should add it too?

**Comment by NinaTanneberger** [comment]
Just pop it in research

**Comment by NinaTanneberger** [comment]
Concept 2 looking better! One of the skins I looked at on WikiMedia uses a similar layout similar to Bootstrap which is good. Now if you can do the other pages and menu bar. Then we can refine from there!

**Comment by jbren48** [comment]
Rightio, Got some plans tonight but I will throw together the rest with this sort of look and have them done asap

**Comment by JacksonGartner** [comment]
Simplistic and manageable with Wikimedia. The implementation of the images nearer the bottom of the page could be changed, possibly a drop shadow or something to make them 'pop'.

Second element form the top in 'Mock_Art' could have the text / arrows moved inwards not to stretch the user to the very edge of their screen. We may also want to keep the text size of 'The Story' down as well. The subscribe form could be resized to make the input field larger so a user can often see their entire email when typing without it scrolling.

Header size on Mock_Profile could be smaller as to not over dominate how small the user's name is at the top. The map and other images could also do with the same highlight / defining with a drop shadow for example.

**Comment by NinaTanneberger** [comment]
Just going to do some dot points:

- Menu bar needs to be on top of page

-  You've done a lot of visual design but not really what we are going to be displaying on the website

- These mockups are a good indication of the look and feel of the website but not the data structure

- Doing a sitemap first would have helped you break down the data into where it should go

- A map image shouldn't be next to the "Story" section - the map should be a key feature elsewhere on the site and easy to access from every page

- RAB as it stands doesn't have a "subscribe" section, maybe it should be a user sign up section

- I believe a search bar should be the first thing you see on the landing section of the web site and it should be accessible across the site on every page

- The about section is ok but maybe should have more links to related data like other members/contributors. Think about using breadcrumbs as well

- In the User Breakdown document there is a list of requirements that should be primary data and then another list which should be secondary which is found on the menu bar

**Comment by NinaTanneberger** [comment]
**I.e. about data: this is what should be viewed on the main page -**
- The Map 
- Ontology Page 
- 3D Viewer 
- Sign Up 
- Search Bar 
- News Feed 
- My Profile 

**This is an example of menu bar items -**
- About
- Find Members
- Library
- Conferences 
- Wiki help 
- Credits 
- Terms of Use
- “My” sections dropdown
