### ISSUE TITLE
Research Wikimedia - looking at style and layout possibilities

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#11]
Run Wikimedia and experiment with what we can change
Research any existing styles that may have achieved similar results

**Comment by JacksonGartner** [comment]
The bootstrap theme which you mentioned elsewhere was the one I was having trouble installing during class. If you have got it working I'd like to continue looking into that theme as it seems to be the best option for our design.

**Comment by NinaTanneberger** [comment]
Yeah I used the Tweeki one which is nice and simple. Just trying to work out how to add content etc. The error I found was that they have written the file path wrong on the installation guide. The folder I had was named Tweeki Master but the file path said Skins/Tweeki/Tweeki.php. So yeah just make sure the path is correct and the correct code is in the Local Settings file.
