### ISSUE TITLE
Research Design Options

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#12]
Research engaging UX UI designs that we can incorporate gathered from similar websites
Share this information with the group to cross reference with Mockup designing

**Comment by JacksonGartner** [comment]
Map focused websites, saved here for later:
https://www.smashingmagazine.com/2010/04/maps-in-modern-web-design/
https://uimovement.com/media/resource_image/image_3165.gif.mp4
https://i.pinimg.com/originals/2a/e4/61/2ae46107dd91077feafd70b6ac5417d9.png
https://designmodo.com/maps-websites/

Is there a document / powerpoint I can add my research too?

**Comment by NinaTanneberger** [comment]
Yes the details are in the presentation issue
