### ISSUE TITLE
Create Templates For MediaWiki

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#28]
Go through sitemap, mockups and Rock Art database. Find pages which will have multiple amounts of its kind ie: profile

Create templates for the pages you have found with HTML and CSS

Focus on the layout and design

Put your completed template files in documentation under **_templates_** 

Add screenshots so we can preview what it looks like

Keep track of your process in the [wiki](https://github.com/rhaubt/rockartdatabase_v3/wiki)

**Comment by rhaubt** [comment]
What is the progress here @GaryLamKa, @jbren48
