### ISSUE TITLE
Skins Research

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#29]
Look at Bootstrap styled Mediawiki skins. 

Test it, try to break it, look at comments on the skin via Github, research its' capabilities.

Find a suitable skin for our project and relay your findings in the wiki [https://github.com/rhaubt/rockartdatabase_v3/wiki](url)

**Comment by rhaubt** [comment]
What is the progress here @JacksonGartner, @jbren48, @GaryLamKa
