### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#3]
Hey all, I've set up a project in google drives for us to keep track of our documents and such. The link is here and also on a sidebar in the wiki section of our project:
https://drive.google.com/open?id=1oudmShcZsidrWBK8lpgfTTDxS7anyUxE

In there you will find documents for team meetings, wireframes, mockups, images, references etc etc.

I have also collated our evaluation and created a document with that as well as my own research and development. I haven't finished some of it but you can find it in the documents folder. 

Once I am finished setting up these things I will convert them to google docs so we can edit things in real time. What I was thinking is if we edit documents we have assigned highlight colours on the text so we can all see what is new and who created it?

A few other things - I thought it would be good to have a team meeting every Tuesday just before class so we can utilise our class time as much as possible. Then when in class just go over our progress with Rob. What do you think?

Also check out [Mockflow ](https://mockflow.com/)- it's for building wireframes and mockups. The cool thing about this site is that you can create a prototype website with links to pages. A non paying user can only have one project open, but if you pay for it it's $9 a month for students. I will be using it for my wireframes so it would be cool if you guys could see them as well, otherwise I can just eport them but the links obviously don't work in the export.

I also found this article useful in my research - it's about redesigning websites 
https://www.toptal.com/designers/web/design-better-foundations

On a personal note, I will add that I am a pretty organised person and I've done a lot of project management as I used to be in the film industry and am accustomed to running big teams. I keep records of team meetings and client interactions not only because it is good practice for our own progress but in the real world you always need to check off with clients that things are correct in case they forget or feel mislead. I also recommend writing a wiki once a week about what you did during each week. It helps a lot towards the end of the project if you need to backtrack or find out how you worked on certain things earlier. 

Cheers guys!

**Comment by NinaTanneberger** [comment]
Ok so I'll be putting main documents in the code section and everything else can stay in the drive if people want to access them - the drive can hold references and examples etc, things that are part of research and development. When things are finalised I'll upload them to Github.

**Comment by JacksonGartner** [comment]
I’m at university right now but I worked on deconstructing the site and creating a site map over the weekend and was planning to just bring my research too class tomorrow but I’ll make sure to upload it once I’m home.

**Comment by rhaubt** [comment]
I created a new folder in the project root folder called 'documentation'. Please place all supporting documents into this folder. Make sure to maintain a logical structure in the documentation folder and web application throughout the project.

The license and readme.md should stay in the root folder. The readme.md should be updated to explain what the project is about, how the application can be run and where any supporting documents can be found. The readme.md essential is the first file that someone looks at that helps users to understand what this project is about and how to find things within the project.

Can someone update the readme.md until tomorrow with some basic descriptions. If you manage documentation within other applications eg Google Docs etc. this should be mentioned in the readme.md

**Comment by JacksonGartner** [comment]
I want be home until later this evening but I’ll make sure to update it then if it hasn’t been already.

**Comment by rhaubt** [comment]
feel free to update this with the group tomorrow at 12pm. I will give you guys 30min tomorrow at the start of the class to discuss and update what you have worked on this week.

**Comment by rhaubt** [comment]
Maybe we can leave this issue open throughout the duration of the project as our general 'Communication Tool'. Make sure to close all other issues once the tasks have been completed by all assigned members.

Please make sure to have a look at all the new issues I have posted following up on yesterdays meeting. Once you had a look at the issue, please respond to the issue sharing your findings with the rest of the team. The tasks for this week so far include:

- Research other Cultural Heritage sites that try to centralize global cultural information in a single location
- Research Structured Data and Linked Data
- Download and install MediaWiki on your local host and familiarise yourself with modifying the look and feel of the platform

**Comment by NinaTanneberger** [comment]
Hey all can we meet at 11:30 this coming lesson so we can go over the presentation before class?

**Comment by rhaubt** [comment]
Just a reminder for the group that you also need a 'project plan' eg Gant Chart, Kanban etc. showing:

- timeline
- milestones
- due dates
- tasks
- task allocation / team members

You can use and display this in GitHub for your presentation or a separate document.

Further, please ensure to clearly outline the following elements in your presentation:

- Project Overview
- Aims / Outcomes
- Deliverables / Desirables
- risk management plan (at least three scenarios eg 1. achieved all goals 2. focus on core functions but needs improvements 3. project did not work, what can we reuse in the future?)
- costs (did you use any commercial applications, imagery etc.)
- other comments

**Comment by rhaubt** [comment]
Feel free to use the 'Wiki' for your presentation instead of a powerpoint etc.

**Comment by NinaTanneberger** [comment]
Right. Well the presentation is already half done so I think we will just leave it as a PowerPoint. I didn't know we had to do all of that, I asked about Gantt charts and such a few weeks ago. Can we devide the presentation segments up amongst the group please? Comment which sections you're going to do or I'll assign them. Also Gary I haven't heard anything from you, can you input in chats please

**Comment by NinaTanneberger** [comment]
Ok I've put in milestones for us, it's a start and it will be updated weekly after class as we will constantly be having new items added. You have all been invited to the Gantt chart I set up for an active at-a-glance timeline, you can also view a snap shot of the current schedule. If the snapshot is updated it will show on this link and the link is also on the readme file for the project. Please don't hesitate to add milestones to the project, just make sure you add a brief description, assign members and label it accordingly. I put in what I could think of so far but since I've never done a project like this in terms of the database I'm a little unsure of the procedure.

https://instagantt.com/shared/s/854237321341041/latest

**Comment by NinaTanneberger** [comment]
I will be absent in week 5 for dental surgery but I can Skype in, talking will just be difficult.

**Comment by NinaTanneberger** [comment]
### Project Update

This week Jack has been unwell and has not been able to complete his work. 

I have also been unwell and as a result am late with uploading the MediaWiki extensions. I will be doing so shortly and adding some things to the wiki tonight.

Consequentially much of our work load for the week has not been done which is a setback. I propose that we work on it this week and try to get as many pages set up as possible between us. 

I think it would be good if everyone **posts an update status** on their tasks for this week just to get a grasp of where we are at even if not much has been done - so research notes, experimental notes with MediaWiki etc. From there we can assess what needs to be done and if Jack is too sick this week, divide his tasks amongst ourselves.

On top of that we will have more tasks to do - we really should have a meeting this week even if it is virtual - maybe around Thursday so we can catch up on our work beforehand?

Please give a thumbs up that you've read this and comment :-)

**Comment by rhaubt** [comment]
Thank you Nina, can everyone please provide an update what they have been working on even if the progress has been minimal!! If you have not done anything this week please also let us know. This is important so that the rest of the team knows what they have to work with.

**Comment by JacksonGartner** [comment]
I was only able to do some fiddling around with the current MediaWiki extension on my computer throughout the week to figure out what was possible and I wasn’t able to start working on the header / footer until I got a hold of the mwSetup_v1 from Nina, I’ll be working further on this today.

**Comment by rhaubt** [comment]
Thank you Jackson, can all other participants please update their progress? @GaryLamKa @jbren48

**Comment by rhaubt** [comment]
@NinaTanneberger you are doing a great job so far trying to organise the project and taking the initiative. Can you try and do the following:

- install GitHub Desktop client on your machine (PC / MAC)
- create a new repository in GitHub and select a folder in htdocs on your machine
- install a mediawiki instance in the htdocs > rockartdatabase folder on your local machine
- commit the changes using GitHub Desktop - this should push the mediawiki on your machine to GitHub

We can then all "Clone" the repository on our own local machines and that way we all have the same version of GitHub.

If you guys need help, please let me know and we can maybe organise a time online together and I can run you through the steps.

**Comment by NinaTanneberger** [comment]
Yeah I've tried to use Github Desktop but I can't do anything with it? I'm pretty confused. Will have to look at some tutorials on how to use it properly tomorrow. What I mean is I can see some files in the project but can't upload or view issues. Will update tomorrow when I look again.

**Comment by rhaubt** [comment]
@NinaTanneberger The Desktop client does not handle issues, it only handles your files in the repository. Issues, projects etc needs to be managed on the GitHub website or, there is an app that you can download for iOS and Android that lets you manage issues and projects.

You should manage your files on you local host using eg MAMP or XAMPP as usual in your htdocs folder. Use the GitHub client only to commit updates to GitHub, fetch updates from GitHub or create branches - new repositories.

Here are some step by step instructions:

1. Open GitHub Desktop
2. Go to File > Clone Repository
3. Select the rockartdatabase_v3 repository to clone (this will copy it on your computer)
4. Select a destination on your computer to save the repository (use eg htdocs, the folder you are using with MAMP or XAMPP)
5. This should now clone all files to your local repository

You can now work on your local machine with these files and when you are happy with updates / changes etc. you can "Commit" these updates to GitHub.

Everyone should follow the steps above. Once you committed the changes, everyone else can now fetch the latest version.

Again, issues and projects are still managed on the GitHub Website itself, while the files can now be worked on locally.

Let me know if that made sense. :)

**Comment by JacksonGartner** [comment]
I have successfully connected the Desktop client to this repository, once I get this installation issue with mwSetup worked out I'll push it all to this repository myself and that should allow others to get it all working too.

**Comment by rhaubt** [comment]
This looks great @JacksonGartner. And I see @NinaTanneberger you created your first branch!! :)

@GaryLamKa @jbren48 can you both please also add a comment here once you cloned this repository onto your local machine (use GitHub Desktop). If anyone is still having problems cloning this repository please let me know :) Happy to assist.

**Comment by NinaTanneberger** [comment]
Ok I've pushed the mediawiki folder to the master commit in our repository. Jackson when you upload changes from yours please name the file with a "V2" at the end of it. I will get onto version control this week, just wanted to chat to Rob about that. Can everyone please update on what they have been doing so we have an idea on where we stand?

**Comment by NinaTanneberger** [comment]
Hey all it's study week but it is important that we meet. Rob will you be on campus at all? I wouldn't mind touching base as a group. Please comment.

**Comment by rhaubt** [comment]
I won't be on campus tomorrow. Maybe the group can use the time to catch up and reevaluate the due dates and outcomes of this project.

**Comment by JacksonGartner** [comment]
I'll be available all week.

**Comment by GaryLamKa** [comment]
i'll be there

**Comment by NinaTanneberger** [comment]
Yeah let's just meet at uni at noon. Sound good?

**Comment by JacksonGartner** [comment]
Tomorrow? Make sure to check with Jack, may need to message on Facebook.

**Comment by JacksonGartner** [comment]
But I'm good with that, I'll have to leave by 5 but having the afternoon to work on this together would be good.

**Comment by NinaTanneberger** [comment]
Yeah problem is I need my pc to do my stuff. I just wanted to touch base really, but I need to spend my time trying to fix this. How about we just discuss our work for the week on github and I'll try and get the install working. Then meet later in the week?

**Comment by GaryLamKa** [comment]
yes sure, i will post the Markdown tag on wiki later and an issues that I got a problem with

**Comment by NinaTanneberger** [comment]
OK cool. I'm not going to be able to come in today after all. So maybe we can just discuss online for the week
