### ISSUE TITLE
Add "How To" for front end development in Wiki

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#34]
Details on how to add CSS and HTML to a MediaWiki through MediaWiki site.

Brief outline with syntax details put into a Github Wiki Page

**Comment by NinaTanneberger** [comment]
Guys this is really important. I have no idea how to edit pages with HTML and CSS which means i can't figure out how extensions work. If I dump the code you have put in the [wiki ](https://github.com/rhaubt/rockartdatabase_v3/wiki/Home-Page-Guide) it only shows a wall of text.

**Comment by JacksonGartner** [comment]
Once I am home from work I'll write up another wiki article with simply instructions on how to create / edit a page.
