### ISSUE TITLE
mySetup_v1 Installation error

### ISSUE THREAD

**Issue by JacksonGartner** [rhaubt/rockartdatabase_v3#37]
After following the wiki guide and extracting the mediawiki file to htdocs and starting up xamp I am presented with the following when opening through the browser. I have been unable to fix the issue and resorted to a fresh install of the default MediaWiki

> Fatal error: Uncaught Error: Call to a member function getCode() on null in C:\xampp\htdocs\mediawiki-1.31.1\includes\user\User.php:1737 Stack trace: #0 C:\xampp\htdocs\mediawiki-1.31.1\includes\user\User.php(5412): User::getDefaultOptions() #1 C:\xampp\htdocs\mediawiki-1.31.1\includes\user\User.php(3096): User->loadOptions() #2 C:\xampp\htdocs\mediawiki-1.31.1\includes\context\RequestContext.php(336): User->getOption('language') #3 C:\xampp\htdocs\mediawiki-1.31.1\includes\Message.php(380): RequestContext->getLanguage() #4 C:\xampp\htdocs\mediawiki-1.31.1\includes\Message.php(1290): Message->getLanguage() #5 C:\xampp\htdocs\mediawiki-1.31.1\includes\Message.php(842): Message->fetchMessage() #6 C:\xampp\htdocs\mediawiki-1.31.1\includes\Message.php(934): Message->toString('text') #7 C:\xampp\htdocs\mediawiki-1.31.1\includes\exception\MWExceptionRenderer.php(199): Message->text() #8 C:\xampp\htdocs\mediawiki-1.31.1\includes\exception\MWExceptionRenderer.php(299): MWExceptionRenderer::msg('dberr-problems', 'Sorry! This sit.. in C:\xampp\htdocs\mediawiki-1.31.1\includes\user\User.php on line 1737

**Comment by JacksonGartner** [comment]
xampp*

P.S. Default installation of MediaWiki is working fine, unsure how this mwSetup_v1 is supposed to work but does it require I have a Php database setup for it prior - that may be an issue?

**Comment by JacksonGartner** [comment]
Unsure what I should do with my work for the Header / Footer in the meantime, you mentioned it looks quite difficult to achieve this Nina so should I try and make it work on a default version of MediaWiki with my own extensions or wait for this bug to be resolved so I can do it with the group installation?

**Comment by NinaTanneberger** [comment]
So what you should do with my wikinmedia folder is place it in ht docs and open its local settings file. The next version will have proper naming so you don't get confused but it SHOULD work by doing so. I replaced it on my own pc and it worked. Additionally you need to install composer. Did you install composer?

**Comment by NinaTanneberger** [comment]
So what you should do with my wikinmedia folder is place it in ht docs and open its local settings file. The next version will have proper naming so you don't get confused but it SHOULD work by doing so. I replaced it on my own pc and it worked. Additionally you need to install composer. Did you install composer?

**Comment by JacksonGartner** [comment]
I reinstalled composer and redownloaded the mwSetup and it seems to be working, unsure what the issue was but it's gone now. Thanks.

**Comment by NinaTanneberger** [comment]
Yay!
