### ISSUE TITLE
Week 2 Update

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#4]
Hey all,

This is just an update so that we know where we stand and what's happening over the next week.

**Team status:**
No specific roles – front end and back end   
Team meeting before class – 11:45  library   
Research existing websites and gather ideas for design and layout
Front end designing wireframes for next week class, looking at colour schemes
Back end research for Wiki page and metadata issues

You guys are free to do the wireframes how you like, I can either set up a Mockflow project which can have multiple pages with built in links to create a live prototype or you can do it by other means. You will need to communicate about your designs so you get similar layouts so I think it's a good idea. For this I will need your email addresses to share the workspace with you. Let me know!

Wireframes will need to be locked in by the end of next week's class so we can move forward with the mockups. 

I think another thing we should do in next week's class is begin putting together our presentation of the project so when we finish the mockups we do not have to write the entire thing.

Thanks!

**Comment by NinaTanneberger** [comment]
Has Jack been added to the team? I can't see him on the list

**Comment by rhaubt** [comment]
he has to accept the invitation first. maybe someone can send him an email or message.

**Comment by JacksonGartner** [comment]
I’ve sent him a message.
