### ISSUE TITLE
Research Cultural Heritage Websites and write a brief comparative analysis 

### ISSUE THREAD

**Issue by rhaubt** [rhaubt/rockartdatabase_v3#5]
The idea of the Global Rock Art Database is that professionals and people with a general interest in rock art can find information about rock art worldwide projects and sites. Users can upload information to the platform or optionally simply provide links back to their own websites.

Uploading data to the rock art database gives users access to the semantic metadata functions that we discussed in class while simply providing links allows users to find their websites as a resource but doesn't allow them to utilise the advanced search functions (as they would need to enable semantic metadata functions on their own website).

This way the Global Rock Art Database tries to link international rock art projects in a single online platform and aims to provide the world's largest online register for rock art.

As discussed in todays class, I would like you all (individually) to research Cultural Heritage projects with a similar approach. How do other Cultural Heritage projects on the internet centralize data collections and what methods do they use to manage and showcase this information?

A few examples to get you started:

**International**
- https://whc.unesco.org/en/list/
- https://artsandculture.google.com/
- https://globalheritagefund.org/what-we-do/preservation-by-design-2/ 
- https://globalheritagefund.org/what-we-do/projects-and-programs/

**European**
- https://www.europeana.eu/portal/en

**Australian**
- http://www.environment.gov.au/cgi-bin/ahdb/search.pl
- https://environment.ehp.qld.gov.au/heritage-register/
- https://www.environment.nsw.gov.au/heritageapp/heritagesearch.aspx

**Interactive and 3D**
- https://www.cyark.org/

**Specialised Heritage Projects**
- https://projectmosul.org/

**Heritage Projects with a semantic metadata approach**

- http://www.britishmuseum.org/about_us/news_and_press/press_releases/2011/semantic_web_endpoint.aspx
- https://public.researchspace.org/resource/Start

Please include the following:
- what is the theme of the project you are looking at
- what information does the project collect and how do they collect this information
- how is the information managed
- how is the information presented
- what makes the site engaging (design elements, presentation, interaction, narrative etc)

**Comment by NinaTanneberger** [comment]
I went pretty overboard with this topic as there was a lot to look at it. You can find my full report in the _**research**_ folder
