### ISSUE TITLE
Infobox Options

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#53]
### **For some time I have struggled with the Infobox installation:**

Essentially I have followed all of the [instructions](https://trog.qgl.org/20140923/setting-up-infobox-templates-in-mediawiki-v1-23/) on the Infobox installation but cannot successfully import it to MediaWiki. There have been several options you can read about in my [progress blog](https://github.com/rhaubt/rockartdatabase_v3/wiki/Nina-Tanneberger-Progress-Log) under Week 9 - Infobox Issues .

After many attempts I believe the best option is to look for other alternatives to this issue. I have found an extension called [Capiunto](https://www.mediawiki.org/wiki/Extension:Capiunto/Infobox) which also has an Infobox. I have installed this extension and it is ready to use - so **Front End** guys - it's up to you to  see if it works. If it does not, I will research other alternatives.

**Comment by NinaTanneberger** [comment]
Task handed over to @jbren48  

* Look at  [install](https://trog.qgl.org/20140923/setting-up-infobox-templates-in-mediawiki-v1-23/) from Wikipedia and see if you can work through the bugs
* Look at Capiunto extension for Infobox and find an infobox solution
* If these options fail look into other options

**Comment by jbren48** [comment]
After first trying out the Scribunto extension I found the same issue you were dealing with, for some reason the extension has a problem working with templates, So I moved onto the next extension Capiunto and found that it actually needs Scribunto to function.

> Provides basic Infobox functionality for Scribunto.

So I will aim to either fix Scribunto or find another infobox alternative for the team.

**Comment by NinaTanneberger** [comment]
Yes because you are meant to download the repository that I created on GitHub with all the extension installs. See the Clean Install MediaWiki issue.
