### ISSUE TITLE
Jackson Tasks Due Week 10

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#54]
Create Wiki documentation with skin installation and information - not just on how to install but also how to use it, how to edit CSS within MediaWiki etc.

Navigate from the Master repository to ``rockartdatabase_v3/tree/master/sitePages``. There you will find the first few pages for the website set up. Within these pages, place your code within the allocated pages. There will be more - this is simply an indicator.

Upload logos and other images into the master MediaWiki folder named [newInstall](https://github.com/rhaubt/rockartdatabase_v3/tree/master/newInstall)

Home page to present in week 10 class.

View all current issues and apply yourself to their requirements.

**Comment by JacksonGartner** [comment]
Was newInstall created from my latest upload of mediawiki-1.31.1 or was it a fresh install (meaning I'll need to re-add images / update LocalSettings @NinaTanneberger?

**Comment by JacksonGartner** [comment]
Is `rockartdatabase_v3/tree/master/sitePages` where we place our individual page CSS / HTML for the page design / layout? Just clarifying @NinaTanneberger.

**Comment by NinaTanneberger** [comment]
Fresh install of the entire thing, so you will just need to add the images via Github desktop and it will refresh across the entire project.

And yep the site pages are for your code for the individual pages

**Comment by JacksonGartner** [comment]
To-do:
1. Delete mediawiki-1.31.1 files on GitHub.
2. Create Wiki guide for CSS / HTML MediaWiki page creation.
3. Add homepage HTML / CSS to `sitePages`.
4. Install `newInstall` and re-add content.

**Comment by NinaTanneberger** [comment]
Does that comment mean the tasks are done?

**Comment by JacksonGartner** [comment]
Done:
1. Delete `mediawiki-1.31.1` files on GitHub.
2. Create Wiki guide for MediaWiki page creation (CSS / HTML).
3. Add homepage HTML / CSS to `sitePages`.

Ongoing: 
1. Install `newInstall` and re-add content.
2. Home page design.
