### ISSUE TITLE
Gary Tasks Due Week 10

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#55]
Navigate from the Master repository to rockartdatabase_v3/tree/master/sitePages. There you will find the first few pages for the website set up. Within these pages, place your code within the allocated pages. There will be more - this is simply an indicator.

Your pages due in week 10 class are:
Company
Profile

Work with Jack on updating the wiki with information about how to edit pages with markdown/html/css.

View all current issues and apply yourself to their requirements.

**Comment by GaryLamKa** [comment]
Will upload both page tmr, thanks
