### ISSUE TITLE
Learning about metadata and structured data

### ISSUE THREAD

**Issue by rhaubt** [rhaubt/rockartdatabase_v3#6]
Please familiarize yourselves with structured data. While this task will be mainly important for Nina, I would like you all to have a general idea about the concept.

Here are some useful links to introduce you to metadata and structured data and the Semantic Web using linked data as discussed by Tim Berners-Lee:

- https://developers.google.com/search/docs/guides/
- https://www.youtube.com/watch?v=B0BA7Tswavs
- https://www.youtube.com/watch?v=V6BR9DrmUQA

**Comment by NinaTanneberger** [comment]
Added to the research folder in documentation
