### ISSUE TITLE
Clean Install MediaWiki

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#62]
Follow instructions from [Nina's instructions](https://github.com/rhaubt/rockartdatabase_v3/wiki/MediaWiki-Repository-Versioning)

Comment on this thread for troubleshooting issues.

**Comment by NinaTanneberger** [comment]
Currently troubleshooting this, something has gone wrong with the database so I will have to do a complete reinstall and re-upload to our repository. Please make sure you watch this thread so you know when I have fixed the bugs @jbren48 @JacksonGartner @GaryLamKa

**Comment by JacksonGartner** [comment]
Is `install_v4` ready to test @NinaTanneberger?

**Comment by NinaTanneberger** [comment]
I'm almost there... I am running one more test, fingers crossed it's ready

**Comment by NinaTanneberger** [comment]
Ok I have it working on two computers but not a third so let's see if it works on yours.

`Uninstall xampp`. Once you do that, navigate to where it was installed and there will be a residual folder named `xampp` still there. Delete that.

Make sure you have removed the repository from `Github Desktop Client` so you have a new install.

When you clone the repository, make sure you set the file path correctly. In `xampp/htdocs` you need to create a folder called "GitHub". Then when you select the repository to clone you need to direct the files there. So the path would be for example `c:/xampp/htdocs/GitHub/` and Github will create the folder `rockartdatabase_v3`.

Once the files are in, run the file `install_v4` from the xampp control panel.

That probably won't work so comment with your error here.

You have to follow my instructions exactly or I can't know where the errors are. I know what the issue is but it has it has not been consistent across all of my machines which is why I'm stuck,

@JacksonGartner @GaryLamKa  @jbren48

**Comment by JacksonGartner** [comment]
Will test this today and get back to you.

**Comment by NinaTanneberger** [comment]
I now have it working on all three devices. Some weird stuff was happening and the workaround is odd. Hopefully it works for you.

**Comment by JacksonGartner** [comment]
`Fatal error: Uncaught Error: Call to a member function getCode() on null in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php:1737 Stack trace: #0 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(5412): User::getDefaultOptions() #1 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(3096): User->loadOptions() #2 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\context\RequestContext.php(336): User->getOption('language') #3 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(380): RequestContext->getLanguage() #4 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(1290): Message->getLanguage() #5 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(842): Message->fetchMessage() #6 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(934): Message->toString('text') #7 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\exception\MWExceptionR in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php on line 1737`

**Comment by JacksonGartner** [comment]
Seems to be the same error as before @NinaTanneberger

**Comment by NinaTanneberger** [comment]
OK. In the Site Pages folder of our project next can you create a file. Copy and paste your LocalSettings.php code. Also if you can upload a screenshot of your repository install location with the file path clearly displayed

**Comment by NinaTanneberger** [comment]
Ok I think I have figured something out, maybe it's something to do with the database, it's very odd. 

Assuming you have followed every instruction, once you install the GitHub repository and run the code you will get the error message.

- **Remove** but don't delete the `LocalSettings.php` file from the `install_v4` folder. 
- Run the `install_v4` project and now you should have a clean MediaWiki install setup. Go through the setup and download the LocalSettings.php file that it generates. Do not check anything or make any modifications to the install. The only thing you need to input is the database name **_The Rock Art Repository_** plus the user and password details. Ignore the .php file it generates and leave it where it is.
- Now **re-add** your LocalSettings.php file from earlier into the `install_v4` folder and run the project.

**Comment by NinaTanneberger** [comment]
This is a top priority issue guys, I need to hear from you all.

**Comment by JacksonGartner** [comment]
I followed the instructions above and received the same error it seems
`Fatal error: Uncaught Error: Call to a member function getCode() on null in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php:1737 Stack trace: #0 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(5412): User::getDefaultOptions() #1 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(3096): User->loadOptions() #2 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\context\RequestContext.php(336): User->getOption('language') #3 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(380): RequestContext->getLanguage() #4 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(1290): Message->getLanguage() #5 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(842): Message->fetchMessage() #6 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(934): Message->toString('text') #7 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\exception\MWExceptionR in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php on line 1737`

**Comment by NinaTanneberger** [comment]
That's really weird

**Comment by NinaTanneberger** [comment]
Can you upload a screen shot of your install_v4 folder with the file path visible at the top. Also upload the localsettings.php code please :)

**Comment by NinaTanneberger** [comment]
Can you can you install a fresh mediawiki, generate a localsettings.php and push it to the repository please

**Comment by jbren48** [comment]
I got the same result unfortunately,


Fatal error: Uncaught Error: Call to a member function getCode() on null in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php:1737 Stack trace: #0 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(5412): User::getDefaultOptions() #1 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(3096): User->loadOptions() #2 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\context\RequestContext.php(336): User->getOption('language') #3 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(380): RequestContext->getLanguage() #4 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(1290): Message->getLanguage() #5 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(842): Message->fetchMessage() #6 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(934): Message->toString('text') #7 C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\exception\MWExceptionR in C:\xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php on line 1737

I will get the the code and screenshot now

**Comment by jbren48** [comment]
`Fatal error: Uncaught Error: Call to a member function getCode() on null in C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php:1737 Stack trace: #0 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(5412): User::getDefaultOptions() #1 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php(3096): User->loadOptions() #2 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\context\RequestContext.php(336): User->getOption('language') #3 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(380): RequestContext->getLanguage() #4 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(1290): Message->getLanguage() #5 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\Message.php(842): Message->fetchMessage() #6 C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3 in C:\Users\Jack\Desktop\Xampp\htdocs\GitHub\rockartdatabase_v3\install_v4\includes\user\User.php on line 1737`

Same Error unfortunately and yes I definitely did that last step

**Comment by NinaTanneberger** [comment]
So weird because it works on all of my devices even if I uninstall and reinstall. Can you try creating a new user and install it all there in a location other than c:/xampp

**Comment by NinaTanneberger** [comment]
I made a [video](https://youtu.be/Wp9dbyZa3XA) that shows it works on my PC and two other devices.

I'm not sure why it isn't working for you guys.

**Comment by JacksonGartner** [comment]
I am now confused after watching https://www.youtube.com/watch?v=Wp9dbyZa3XA. At 2:44 you don't change the database name and then you proceed to change the Wiki name to the `The Rock Art Database`. Both these steps were absent from your instructions from three days ago.

> Do not check anything or make any modifications to the install. The only thing you need to input is the database name **_The Rock Art Repository_** plus the user and password details.

**Comment by NinaTanneberger** [comment]
The Wiki name is completely irrelevant as that setup is not used, it only generates the .php. If you don't fill it in it won't let you pass

**Comment by NinaTanneberger** [comment]
And yes I can see I wrote it wrong up above but I have done this installation about fifty times this week so I'm sorry if I messed up a line >:( I don't see you guys trying to help me troubleshoot it

**Comment by JacksonGartner** [comment]
It's fine, I was just going wrong with changing the database name, when I shouldn't have been.

**Comment by JacksonGartner** [comment]
The install_v4 is now working for all of us. I'll test out the templates and write up any bugs I find tonight as well as update the GitHub version of the Home page.
