### ISSUE TITLE
Jack Tasks Due Week 11

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#64]
Complete the Infobox task and report back about your findings.

Continue working on your templates - Rock Art Page, Company - by Saturday

**Comment by jbren48** [comment]
Update on InfoBox task has been posted on the Infobox Issue.

**Comment by NinaTanneberger** [comment]
Rock Art Display page wasn't updated until 10pm Monday evening. Two days late
