### ISSUE TITLE
Left side of homepage

### ISSUE THREAD

**Issue by JacksonGartner** [rhaubt/rockartdatabase_v3#67]
Have you had any luck figuring out how to get around this problem? I assume it related to the Tweeki skin but have had no luck locating the padding, etc.

**Comment by NinaTanneberger** [comment]
Don't forget to assign people to issues, use labels, projects and milestones 👍

**Comment by NinaTanneberger** [comment]
Ah yeah. If you switch to desktop version you can

**Comment by NinaTanneberger** [comment]
Is anyone going else going to look at this issue @jbren48 @GaryLamKa? This falls under front end development issues.

**Comment by NinaTanneberger** [comment]
What is the actual issue here? It doesn't say

**Comment by JacksonGartner** [comment]
We discussed it in class and Robert said he was going to have a look at it - I haven't heard from him. I'll close this issue as no solution has been found and it's too late to worry about it now.

**Comment by NinaTanneberger** [comment]
Even if it is discussed in class, if it as an issue that requires GitHub contribution you need to detail what the problem is
