### ISSUE TITLE
MedaWiki Look and Feel

### ISSUE THREAD

**Issue by rhaubt** [rhaubt/rockartdatabase_v3#7]
If we decide on using MedaWiki as the platform for this project, please have a look on how you can modify the look and feel of the Wiki. Similar to Wordpress and Drupal you can make changes to the Wiki using Skins and Extensions. This article gives you a brief overview of how to customize a MedaWiki:
- https://www.lifehacker.com.au/2009/11/customise-mediawiki-into-your-ultimate-collaborative-website/

Please download MediaWiki here and install on your local host using MAMP or XAMP:
- https://www.mediawiki.org/wiki/Download

Once you have install the Wiki on your computer have a look at the different available Skins and / or feel free to build your own designs:
- https://www.mediawiki.org/wiki/Manual:Gallery_of_user_styles

**Comment by JacksonGartner** [comment]
I created a local Apache and MySQL server and installed MediaWiki. Spent some time changing / modifying skins and updating content. This looks like a good platform to create the new rock art website with.

**Comment by NinaTanneberger** [comment]
Nice! Can you upload some screen shots?

**Comment by NinaTanneberger** [comment]
I did some research, downloaded the files and played with the online CSS editor. I had difficulty actually editing the skins in the folder as the instructions I followed seemed to be wrong or outdated. Something I want to explore more particularly with what we actually want to do with our design and using an interactive map etc. The use of extensions is something to be explored and after looking at the code for them I can see the potential of us creating the interface we need to make it work. Keen to see what you guys came up with.

**Comment by JacksonGartner** [comment]
I'll bring it all on my laptop tomorrow, I decided to do my CIU presentation this week however instead of later so I've been focusing on that so my work this week for DWD has been lesser. Will go over all progress tomorrow at 11:45.

**Comment by rhaubt** [comment]
As requested here is a guide for using skins in mediawiki:

https://www.mediawiki.org/wiki/Manual:Skins
https://www.mediawiki.org/wiki/Manual:Skinning_Part_1
https://www.mediawiki.org/wiki/Manual:Skinning_Part_2
https://www.mediawiki.org/wiki/Manual:Skinning_Part_3
