### ISSUE TITLE
Correct Tweeki Layout for Testing + Logo

### ISSUE THREAD

**Issue by JacksonGartner** [rhaubt/rockartdatabase_v3#72]
Please make sure to visit https://github.com/rhaubt/rockartdatabase_v3/wiki/Tweeki-Layout-Edit-Guide and apply these changes before finalising your template testing.

Could @NinaTanneberger also upload the latest logo (with correct sizing - small, just for header) to the github / update localsettings with its filepath. Thanks.

**Comment by NinaTanneberger** [comment]
Done and pushed to the repository 👍
