### ISSUE TITLE
Template to Page

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#73]
So I'm completely stuck on using the templates. I've done the curly brackets to include my info on my wiki page and it works, but it also changes the information on the template. I am trying to follow the guides for MediaWiki online... 

The placeholders have 3 curly brackets each ie: {{{Name}}} but I can't get it working with 3.
If I change it to 2 it appears on both my page and my template {{name}}...

How are you guys going with the testing? If anyone has it working I'd love to see the code.

**Comment by JacksonGartner** [comment]
For Jack's display page I created a page called Template:Display and copied his code from github into that. I then created another random page (mine was called TestDisplay) and did this, Display at the top to call the template and the About / Paintings are in the {{{ }}}:
```
{{Display

|

About=Hello

|

Paintings=Test

}}
```

**Comment by jbren48** [comment]
I'm a bit confused to what you're asking, if you're talking about removing the coloured backgrounds that's just a temporary placeholder for where images go

**Comment by NinaTanneberger** [comment]
No, I'm talking about taking a template and using it to create a page. Like I want to create a page for myself and it would be a profile page. That's what we are meant to do.

**Comment by JacksonGartner** [comment]
I don't know how that's possible, have you tried using Jack's template?

**Comment by jbren48** [comment]
What template are you using? This doesn't look like any of Gary's designs.

I have tested them and they seem to be working for me I will add a step by step guide in the wiki.
