### ISSUE TITLE
Infobox Working

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#74]
Find a solution for the infobox input - we need a working version with categories etc.

**Comment by NinaTanneberger** [comment]
What is the progress on this @jbren48 @GaryLamKa ? This is high priority.

**Comment by NinaTanneberger** [comment]
What's up with the info box guys??

**Comment by jbren48** [comment]
Sorry, Yes I will talk about my findings in class

**Comment by NinaTanneberger** [comment]
Working and added to website templates
