### ISSUE TITLE
Apply Global CSS 

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#77]
Work on the Global CSS through the Tweeki.css special page.

Ensure all templates and pages are uniform - see if the editing pages, special pages etc are also the same colour.

**Comment by JacksonGartner** [comment]
The header / footer are consistent across the website and the global CSS is in place with a wiki available for all members to update. There is no CSS on the RockArtDisplay page for me to change, the profile page's CSS has not be separated from the HTML yet. When you work on separating the CSS and HTML for the profile page @GaryLamKa could you also please go through your colours on both templates and uniform them with ones used in the Tweeki / Homepage CSS sections (https://github.com/rhaubt/rockartdatabase_v3/wiki/Tweeki-CSS-Edit-Guide), feel free to also use an earthy / rocky brown colour you like for small highlights on the page (maybe something like #723500).

**Comment by NinaTanneberger** [comment]
Can you add a file in the **sitePages** folder with your CSS rules?

**Comment by NinaTanneberger** [comment]
Do you think we can add some colour to the skin? Just looks quite plain. Whats says the client? @rhaubt

**Comment by JacksonGartner** [comment]
I just kept it simple as I think Rob wanted, functionality over pretty. I think plain allows it to remain easy to understand and navigate.

**Comment by NinaTanneberger** [comment]
Ok. My only real nitpick is that the text on the navbar needs to be a different colour, maybe white. It's a bit hard to distinguish

**Comment by JacksonGartner** [comment]
I asked rob about this a few weeks back when I initially changed the header colour as I noticed it too. Apparently its quite a bit of work to change the hyperlinks so I didn't pursue it.

**Comment by NinaTanneberger** [comment]
I think I managed to do it on my CSS experiment but I can't remember now... I know I could change at least the text to another colour

**Comment by NinaTanneberger** [comment]
I've fixed it, took about 20 minutes. Have a look [here](https://github.com/rhaubt/rockartdatabase_v3/blob/master/sitePages/CSS-Tweeki.txt)
