### ISSUE TITLE
Maps and Ontology Extension

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#79]
Get a working map for the site to install - look at bugs and try to work around them.

Look at more than one option if you are experiencing issues.

See if there is another extension that handles ontology which isn't [Semantic](https://www.mediawiki.org/wiki/Extension:Semantic_MediaWiki).  Could not get Semantic to install.

**Comment by NinaTanneberger** [comment]
Any updates on this?

**Comment by GaryLamKa** [comment]
Sorry for late reply, added page on wiki for the map "Map: Extension:Kartographer" download link and how to use

**Comment by NinaTanneberger** [comment]
Ok, I have installed it and pushed it to the repository for the team. 

Make sure you put a link to the wiki you refer to in your comment so we can find things easily.

Also in the configuration section is that code that is meant to go into `LocalSetttings.php`? Please add a comment about it for users reading the wiki.

Make sure you write your wikis in a formal format, ie: **_"there is few more stuff can be play around but i think it wont be use in the project, but have a look please in case there is something useful but i missed that"_** has no punctuation and speaks in first person.

If you do not require sections on the wiki like **Known Issues** for example, just remove them.

**Comment by GaryLamKa** [comment]
The configuration part is optional, just incase we may needed those function.  
I think that is more like a comment for the group, will take it away.

**Comment by NinaTanneberger** [comment]
Got maps working with Kartographer but could not find a solution for an Ontology extension without Semantic

**Comment by GaryLamKa** [comment]
For the map extension, I can't find a solution for user to add their own location and marker without breaking the template.  The Parameters function will break the map extension code when added in. The only solution I can think of is to add the map usage in the HowToPage, and let the user do the edit on their own. The way to add the map and those marker are only need two set of code (the map itself `<mapframe>` and the marker `"type": "Feature` or `"type": "FeatureCollection"` if more than one marker),  all they need is to add their location pin number.

**Comment by NinaTanneberger** [comment]
We've finished working on the site
