### ISSUE TITLE
Reformat Wikis

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#80]
Pool all of the information we have on our project from the wiki and reformat it into a uniform layout.

Look at existing wiki page information flow ie:MediaWiki

**Comment by NinaTanneberger** [comment]
Look at MediaWiki install guides for an idea of layout for a wiki
EG:  https://www.mediawiki.org/wiki/Extension:Scribunto

**Comment by NinaTanneberger** [comment]
Next week I would like all of the team to edit their wikis to the new format as it is too big a task for me alone. Due date will be Friday for ALL team wiki entries so that I can string it all together. 

@jbren48 @JacksonGartner @GaryLamKa

**Comment by JacksonGartner** [comment]
I'll work on this on Tuesday.

**Comment by JacksonGartner** [comment]
I've reformatted all my wikis, except for 'Jacksons Trimester' as it doesn't relate.

**Comment by jbren48** [comment]
I have reformatted all relevant wikis I have created

**Comment by NinaTanneberger** [comment]
_Ok guys, I've looked at the entire wiki and I have some feedback. A few changes need to be made but most of it is there. Also @GaryLamKa you need to do your pages please. Be aware that I have changed the naming conventions of the wiki but it should still be easy to locate everything._

@jbren48  - you need to add the markup and markdown details for "Editing Pages With Markdown HTML CSS" - it's too vague. You can remove the CSS extension installation and instead add a link to my extension installation guide where the CSS extension details are. Just say that the CSS extension needs to be installed for this to work. You and @GaryLamKa both need to look into this because you both have pages on this topic - you need to decide what to do there.

@jbren48 - Template guide needs to be more thorough. You need to explain the SitePages folder and how the user needs to have these added to their MediaWiki in order for it to work. Have a look at the wiki Jackson wrote for the website on how to use the site.

Instead of vaguely mentioning a wiki in our Github - you need to put a link to it in your phrasing Eg: `After you have created a template create a NEW page on MediaWiki corresponding to the template. For this example, I will be using Garys Profile Template Template:Profile.`

@GaryLamKa - your wikis are very detailed but a bit too big. Just add the relevant information. I can see that you have copy/pasted a lot of your text from MediaWiki wikis - so just add those links in your wikis in the user guide section at the bottom.

@JacksonGartner - On your tweeki css page (i've renamed it "user guide: global css") you need a link to your other wiki about editing pages from the sitepages folder.

**For everyone** - technical requirements needs to be the list of things required for it to run - ie MediaWiki, but also any extensions you used for the process you are describing. Add links in this section to the other github wikis where the information lies ie: if the technical requirement is the project installation or MediaWiki installation - have a link to the wiki within our GitHub. Every wiki should have MediaWiki, xampp/mamp links because they are technical requirements and many of the technical requirements should also have a link to the extension installation.

You guys haven't put in your licenses either - look them up and add them.

Also you should add credits for which team member worked on that wiki - Just add a section in license under a hr tag and your name. 

**Look at my wiki entries as an example of the layout and how to link information to other wikis. Remember this is for users who don't know our project.**

**Comment by GaryLamKa** [comment]
I had go though my wiki page and I trimmed a bit only, I think most of thing I add into the wiki is important.

**Comment by NinaTanneberger** [comment]
@GaryLamKa , your wiki format is still not the right one. Look at this template: https://github.com/rhaubt/rockartdatabase_v3/wiki/Wiki-Template---Github
that is the format you are supposed to write it in, please copy the text and use it for your wiki.

@jbren48 I've deleted your markdown/css wiki becuase Gary covers it in his wiki. If you have no wikis to work on can you please write an infobox wiki. There is an open issue for it.
