### ISSUE TITLE
Add a How to Guide to Website

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#81]
Add a **how to use this website** section on the Homepage for the user. It can just be a description of the site's purpose and then a link to the page with your wiki on how to use it. 

Look at existing wikis as an example of layout and how their information flows.

**Comment by JacksonGartner** [comment]
I'd want to keep it short and sweet, what specifically would we want to say. "The edit button for pages can be found in the views tab - to create a new page simply search the page title - For more information on markdown check out: (link)" etc.? 

I wouldn't want to overwhelm a visitor on their first visit to the website with a wiki's worth of guides.

**Comment by NinaTanneberger** [comment]
More like a link to all of the templates and how to use them, should be MediaWiki:templates or something like that. How to do the mark up, add images etc. Don't write it all up on the home page, do an overview then have a link to the how to guide. Look at the format of existing wikis and follow that layout.

**Comment by NinaTanneberger** [comment]
Completed and added to website
