### ISSUE TITLE
The Global Rock Art Database Test

### ISSUE THREAD

**Issue by NinaTanneberger** [rhaubt/rockartdatabase_v3#82]
Go to [The Global Rock Art Database.](http://www.rockartdatabase.com/v2/)

Select two records, (companies, people) manually punch data in on the site.

How easy or hard it was to input data? What are the issues, does any of this translate to the system we have on our own site?

Give a report on how it all works.

**Comment by JacksonGartner** [comment]
It is quite time consuming to add an entire pages data in, but I wouldn't say it was hard. An issue arose when I came back to edit something I found it sometime's difficult to find the right section in the edit screen when it didn't have a header attached (like 'About' or 'Paintings' as seen on the RockArtDisplay mockup), when it doesn't you sometimes don't know which section you need to change and you have to bounce back and forth to compare the text.

**Comment by GaryLamKa** [comment]
Will do it tmr or tonight if the infobox is done

**Comment by NinaTanneberger** [comment]
I actually don't know how to use the site to do this task, do you need to have a login? @JacksonGartner how did you do it?

**Comment by JacksonGartner** [comment]
I simply went to http://www.rockartdatabase.com/v2/search/ and clicked some locations. Had to copy paste the content and used lorem ipsum for the sections in our template that I couldn't find.

**Comment by NinaTanneberger** [comment]
Hmm OK I'll have a look at that, thanks!
