### ISSUE TITLE
Week 13 Group Presentation

### ISSUE THREAD

**Issue by JacksonGartner** [rhaubt/rockartdatabase_v3#83]
Did we have that Google Slides up yet @NinaTanneberger for us to add our statistics, etc. too for Tuesday?

**Comment by NinaTanneberger** [comment]
Hey guys, here is the link to the slide for the final presentation. I'll be adding my content in today.

https://docs.google.com/presentation/d/1-4Lc4k3qix05MKKwWEdaTM3MxfTDbaLz6do6QIkc0cw/edit?usp=sharing

**Comment by NinaTanneberger** [comment]
We need to do about 2 min each for the overview and summary so if everyone wants to just do two slides for that section, talk about what was achieved and how it worked etc. Then we all have to do two minutes on our own self eval. 

I will just place the slides in alphabetical order and name them so you can just put your info in.

**Comment by NinaTanneberger** [comment]
The unit guide actually says 5-10 minutes per presentation so you don't have to stick to a tight 2 minutes

**Comment by GaryLamKa** [comment]
Can @NinaTanneberger give us the edit access for the powerpoint, I had sent the request. thanks.

**Comment by NinaTanneberger** [comment]
Done now. It should have been open already, I don't know why it wasn't
